import React from 'react'

export default function Product(props) {
    const productList = [
        {
            code:"AC001",
            image:"/img/accesorios/mandoMolon1.png",
            name:"mando de Xbox",
            description:"zi",
            price:"$31.990",
            category:"accesorio",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        },
        {
            code:"",
            image:"",
            name:"",
            description:"",
            price:"",
            category:"",
        }
    ]
  return (
    <div className='product'></div>
  )
}
